name: Mobile LayeredFS Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Base Files
        run: |
          curl -L -o main "https://drive.google.com/file/d/1l2zDd8P4VTNhzPB4Fpx2kRnlGdLrg91W/view?usp=drivesdk"
          
      - name: Run Patcher
        run: python patcher.py

      - name: Organize Folders
        run: |
          mkdir -p atmosphere/contents/0100B0C013912000/exefs/
          mv subsdk0 atmosphere/contents/0100B0C013912000/exefs/
          mv main atmosphere/contents/0100B0C013912000/exefs/
          cp main.npdm atmosphere/contents/0100B0C013912000/exefs/

      - name: Upload Finished Patch
        uses: actions/upload-artifact@v4
        with:
          name: AmongUs-TagNX-Mobile
          path: atmosphere/